spring.application.name=MediCore
spring.output.ansi.enabled=ALWAYS

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=debug

server.port=8080

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.virtual.host=${SPRING_RABBITMQ_VIRTUAL_HOST}

# Custom RabbitMQ
rabbitmq.email.queue.name=${RABBITMQ_EMAIL_QUEUE_NAME}
rabbitmq.exchange.name=${RABBITMQ_EXCHANGE_NAME}
rabbitmq.routing.key.pending=${RABBITMQ_ROUTING_KEY_PENDING}
rabbitmq.routing.key.confirmed=${RABBITMQ_ROUTING_KEY_CONFIRMED}
rabbitmq.routing.key.cancelled=${RABBITMQ_ROUTING_KEY_CANCELLED}

# Mail
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000

#spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

























